# Generated by Django 2.2.1 on 2019-06-03 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0005_auto_20190603_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('verification_id', models.AutoField(primary_key=True, serialize=False)),
                ('verification_image', models.ImageField(upload_to='')),
                ('verification_status', models.IntegerField(default=1)),
                ('verification_expert', models.ForeignKey(on_delete=True, to='User.ExpertUser')),
                ('verification_user', models.ForeignKey(on_delete=True, to='User.NormalUser')),
            ],
            options={
                'verbose_name': '认领专家信息',
                'verbose_name_plural': '认领专家信息',
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('apply_name', models.CharField(max_length=512)),
                ('apply_institution', models.CharField(max_length=1024)),
                ('apply_resource', models.CharField(max_length=1024)),
                ('apply_resourceyear', models.CharField(max_length=8)),
                ('apply_field', models.CharField(max_length=256)),
                ('apply_photo', models.ImageField(upload_to='')),
                ('apply_status', models.IntegerField(default=1)),
                ('apply_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.NormalUser')),
            ],
            options={
                'verbose_name': '申请成为专家信息',
                'verbose_name_plural': '申请成为专家信息',
            },
        ),
    ]
