# Generated by Django 2.0.5 on 2019-05-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('TechResource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitExpertHistory',
            fields=[
                ('Expert_History_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('visit_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.ExpertUser')),
                ('visit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.NormalUser')),
            ],
        ),
        migrations.CreateModel(
            name='VisitResourceHistory',
            fields=[
                ('SciAchi_History_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('visit_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechResource.SciAchi')),
                ('visit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.NormalUser')),
            ],
        ),
    ]
