# Generated by Django 2.2.1 on 2019-05-25 07:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0009_auto_20190525_1517'),
        ('TechResource', '0003_sciachi_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyResources',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('buy_resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechResource.SciAchi')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.NormalUser')),
            ],
        ),
    ]
