# Generated by Django 2.2.1 on 2019-05-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuyResource', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyresources',
            options={'verbose_name': '购买资源', 'verbose_name_plural': '购买资源'},
        ),
    ]
