# Generated by Django 2.2.1 on 2019-06-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20190603_1918'),
        ('TechResource', '0002_auto_20190530_1358'),
        ('Apply', '0001_initial'),
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification_report_comment',
            options={'verbose_name': '评论通知', 'verbose_name_plural': '评论通知'},
        ),
        migrations.CreateModel(
            name='Notification_verification_expert',
            fields=[
                ('notification_verifiyxpert_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_message', models.CharField(max_length=100)),
                ('notification_status', models.IntegerField(default=1)),
                ('notification_sendtime', models.DateTimeField(auto_now_add=True)),
                ('notification_receiver', models.ForeignKey(on_delete=True, to='User.NormalUser')),
                ('notification_verification_from', models.ForeignKey(on_delete=True, to='Apply.Apply')),
            ],
            options={
                'verbose_name': '申请成为专家通知',
                'verbose_name_plural': '申请成为专家通知',
            },
        ),
        migrations.CreateModel(
            name='Notification_report_SciAchi',
            fields=[
                ('notification_sciachi_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_message', models.CharField(max_length=100)),
                ('notification_status', models.IntegerField(default=1)),
                ('notification_sendtime', models.DateTimeField(auto_now_add=True)),
                ('notification_receiver', models.ForeignKey(on_delete=True, to='User.NormalUser')),
                ('notification_sciachi_from', models.ForeignKey(on_delete=True, to='TechResource.SciAchi')),
            ],
            options={
                'verbose_name': '成果通知',
                'verbose_name_plural': '成果通知',
            },
        ),
        migrations.CreateModel(
            name='Notification_report_expert',
            fields=[
                ('notification_expert_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_message', models.CharField(max_length=100)),
                ('notification_status', models.IntegerField(default=1)),
                ('notification_sendtime', models.DateTimeField(auto_now_add=True)),
                ('notification_expert_from', models.ForeignKey(on_delete=True, to='TechResource.SciAchi')),
                ('notification_receiver', models.ForeignKey(on_delete=True, to='User.NormalUser')),
            ],
            options={
                'verbose_name': '专家通知',
                'verbose_name_plural': '专家通知',
            },
        ),
        migrations.CreateModel(
            name='Notification_apply_expert',
            fields=[
                ('notification_applyexpert_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_message', models.CharField(max_length=100)),
                ('notification_status', models.IntegerField(default=1)),
                ('notification_sendtime', models.DateTimeField(auto_now_add=True)),
                ('notification_apply_from', models.ForeignKey(on_delete=True, to='Apply.Apply')),
                ('notification_receiver', models.ForeignKey(on_delete=True, to='User.NormalUser')),
            ],
            options={
                'verbose_name': '申请成为专家通知',
                'verbose_name_plural': '申请成为专家通知',
            },
        ),
    ]
