# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-22 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('type', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inst',
            fields=[
                ('inst', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TechResource.Resource')),
                ('estaDate', models.DateTimeField(default='')),
                ('haveexpert', models.ManyToManyField(blank=True, to='User.expert')),
            ],
        ),
        migrations.CreateModel(
            name='SciAchi',
            fields=[
                ('sciAchi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TechResource.Resource')),
                ('sciAchiUrl', models.CharField(max_length=512, null=True)),
                ('abstract', models.CharField(max_length=1024, null=True)),
                ('keywordSeq', models.CharField(max_length=256, null=True)),
                ('value', models.IntegerField(default=0, null=True)),
                ('sciAchiPrice', models.FloatField(default=0.0, null=True)),
                ('sciAchiType', models.CharField(max_length=50, null=True)),
                ('refCount', models.IntegerField(default=0, null=True)),
                ('publishDate', models.DateTimeField(default='', null=True)),
                ('instNum', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TechResource.Inst')),
            ],
        ),
    ]
