# Generated by Django 2.2.1 on 2019-05-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SciAchi',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='No name yet', max_length=512)),
                ('sciAchiUrl', models.CharField(max_length=512, null=True)),
                ('abstract', models.CharField(max_length=1024, null=True)),
                ('keywordSeq', models.CharField(max_length=256, null=True)),
                ('sciAchiPrice', models.FloatField(default=0.0, null=True)),
                ('refCount', models.IntegerField(default=0, null=True)),
                ('publishYear', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': '科技成果',
                'verbose_name_plural': '科技成果',
            },
        ),
    ]
