# Generated by Django 2.0.5 on 2019-05-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SciAchi',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='No name yet', max_length=512)),
                ('sciAchiUrl', models.CharField(max_length=512, null=True)),
                ('abstract', models.CharField(max_length=1024, null=True)),
                ('keywordSeq', models.CharField(max_length=256, null=True)),
                ('refCount', models.IntegerField(default=0, null=True)),
                ('publishYear', models.CharField(max_length=10, null=True)),
                ('like_number', models.IntegerField(default=0)),
                ('visit_number', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': '科技成果',
                'verbose_name_plural': '科技成果',
            },
        ),
    ]
