# Generated by Django 2.2.1 on 2019-05-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechResource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sciachi',
            name='value',
        ),
    ]
