# Generated by Django 2.2.1 on 2019-05-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechResource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sciachi',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
    ]
