# Generated by Django 2.2.1 on 2019-05-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechResource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sciachi',
            name='sciAchiPrice',
        ),
        migrations.AlterField(
            model_name='sciachi',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
