# Generated by Django 2.2.1 on 2019-05-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechResource', '0002_sciachi_like_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sciachi',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
