# Generated by Django 2.2.1 on 2019-05-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0004_auto_20190530_1358'),
        ('UserComment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_report_comment',
            fields=[
                ('notification_comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_message', models.CharField(max_length=100)),
                ('notification_status', models.IntegerField(default=1)),
                ('notification_sendtime', models.DateTimeField(auto_now_add=True)),
                ('notification_comment_from', models.ForeignKey(on_delete=True, to='UserComment.Comment')),
                ('notification_receiver', models.ForeignKey(on_delete=True, to='User.NormalUser')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
            },
        ),
    ]
