# Generated by Django 2.0.5 on 2019-05-25 13:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TechResource', '0003_sciachi_author'),
        ('User', '0006_auto_20190525_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyResources',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('buy_resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechResource.SciAchi')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.NormalUser')),
            ],
            options={
                'verbose_name': '购买资源',
                'verbose_name_plural': '购买资源',
            },
        ),
    ]
