# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-22 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='model_buyresources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='normal_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('passwd', models.CharField(max_length=32)),
                ('point', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=16, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('introduction', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='model_buyresources',
            name='normal_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.normal_user'),
        ),
        migrations.AddField(
            model_name='expert',
            name='expert',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='User.normal_user'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='administrator',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='User.normal_user'),
        ),
    ]
