# Generated by Django 2.0.5 on 2019-05-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='image',
            field=models.ImageField(blank=True, default='timg.jpg', null=True, upload_to=''),
        ),
    ]
