# Generated by Django 2.2.1 on 2019-05-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='passwd',
            field=models.CharField(max_length=1024),
        ),
    ]
