# Generated by Django 2.0.5 on 2019-05-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normaluser',
            options={},
        ),
    ]
