# Generated by Django 2.2.1 on 2019-05-27 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20190527_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normaluser',
            old_name='type',
            new_name='user_type',
        ),
    ]
