# Generated by Django 2.0.5 on 2019-05-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20190529_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmstring',
            options={},
        ),
        migrations.AlterField(
            model_name='expertuser',
            name='name',
            field=models.CharField(default='专家姓名', max_length=64),
        ),
    ]
