# Generated by Django 2.0.5 on 2019-05-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20190530_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='image',
            field=models.ImageField(blank=True, default='timg.jpg', null=True, upload_to='F:\\Python\\Projects\\Software_Engineering\\codePlat\\frontend\\src\\assets'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='sex',
            field=models.CharField(default='男', max_length=32),
        ),
    ]
