# Generated by Django 2.2.1 on 2019-05-23 08:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TechResource', '0002_sciachi_like_number'),
        ('User', '0002_auto_20190522_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyResources',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('buy_resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechResource.SciAchi')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertUser',
            fields=[
                ('expert_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=128, null=True)),
                ('institution', models.CharField(max_length=128, null=True)),
                ('reference_number', models.IntegerField(null=True)),
                ('paper_number', models.IntegerField(null=True)),
                ('H_index', models.IntegerField(null=True)),
                ('G_index', models.IntegerField(null=True)),
                ('field', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LikeResources',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('like_resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechResource.SciAchi')),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('passwd', models.CharField(max_length=32)),
                ('point', models.FloatField(null=True)),
                ('type', models.CharField(choices=[('专家用户', '专家用户'), ('普通用户', '普通用户'), ('管理员', '管理员')], default='普通用户', max_length=16)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('introduction', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='女', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
        migrations.RemoveField(
            model_name='model_buyresources',
            name='normal_user',
        ),
        migrations.AlterField(
            model_name='administrator',
            name='administrator',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='User.NormalUser'),
        ),
        migrations.DeleteModel(
            name='expert',
        ),
        migrations.DeleteModel(
            name='model_buyresources',
        ),
        migrations.DeleteModel(
            name='normal_user',
        ),
        migrations.AddField(
            model_name='likeresources',
            name='liker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.NormalUser'),
        ),
        migrations.AddField(
            model_name='buyresources',
            name='buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.NormalUser'),
        ),
    ]
