# Generated by Django 2.2.1 on 2019-05-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20190527_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='point',
        ),
        migrations.AlterField(
            model_name='expertuser',
            name='corresponding_user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expertuser',
            name='field',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
