# Generated by Django 2.2.1 on 2019-06-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20190530_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_pic', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.RenameField(
            model_name='normaluser',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='expertuser',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expertuser',
            name='name',
            field=models.CharField(default='尚无姓名', max_length=64),
        ),
        migrations.AddField(
            model_name='expertuser',
            name='scholar_id',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expertuser',
            name='visit_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='admin_password',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='expertuser',
            name='field',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='introduction',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
