# Generated by Django 2.0.5 on 2019-05-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20190528_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
