# Generated by Django 2.2.1 on 2019-05-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_normaluser_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='has_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
