# Generated by Django 2.2.1 on 2019-05-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20190524_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='phonenumber',
            field=models.CharField(default='00000000', max_length=11),
        ),
    ]
