# Generated by Django 2.2.1 on 2019-05-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20190525_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeresources',
            name='like_resource_id',
        ),
        migrations.RemoveField(
            model_name='likeresources',
            name='liker_user',
        ),
        migrations.DeleteModel(
            name='BuyResources',
        ),
        migrations.DeleteModel(
            name='LikeResources',
        ),
    ]
