# Generated by Django 2.2.1 on 2019-05-30 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0004_auto_20190530_1358'),
        ('TechResource', '0002_auto_20190530_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitResourceHistory',
            fields=[
                ('SciAchi_History_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('visit_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechResource.SciAchi')),
                ('visit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.NormalUser')),
            ],
        ),
        migrations.CreateModel(
            name='VisitExpertHistory',
            fields=[
                ('Expert_History_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('visit_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.ExpertUser')),
                ('visit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.NormalUser')),
            ],
        ),
    ]
