# Generated by Django 2.0.5 on 2019-05-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('TechResource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeExpert',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('like_expert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.ExpertUser')),
                ('liker_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.NormalUser')),
            ],
            options={
                'verbose_name': '收藏专家',
                'verbose_name_plural': '收藏专家',
            },
        ),
        migrations.CreateModel(
            name='LikeResources',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('like_resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechResource.SciAchi')),
                ('liker_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.NormalUser')),
            ],
            options={
                'verbose_name': '收藏成果',
                'verbose_name_plural': '收藏成果',
            },
        ),
    ]
