# Generated by Django 2.2.1 on 2019-05-30 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20190530_1358'),
        ('Like', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeExpert',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('like_expert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.ExpertUser')),
                ('liker_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.NormalUser')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
            },
        ),
    ]
