# Generated by Django 2.2.1 on 2019-05-22 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normal_user',
            options={'ordering': ['c_time'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='normal_user',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normal_user',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='normal_user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='女', max_length=32),
        ),
        migrations.AlterField(
            model_name='normal_user',
            name='point',
            field=models.FloatField(null=True),
        ),
    ]
