# Generated by Django 2.0.5 on 2019-05-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_normaluser_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyresources',
            name='buy_resource_id',
        ),
        migrations.RemoveField(
            model_name='buyresources',
            name='buyer_id',
        ),
        migrations.RemoveField(
            model_name='likeresources',
            name='like_resource_id',
        ),
        migrations.RemoveField(
            model_name='likeresources',
            name='liker_user',
        ),
        migrations.AlterModelOptions(
            name='administrator',
            options={'ordering': ['admin_id'], 'verbose_name': '管理员', 'verbose_name_plural': '管理员'},
        ),
        migrations.AlterModelOptions(
            name='expertuser',
            options={'ordering': ['expert_id'], 'verbose_name': '专家', 'verbose_name_plural': '专家'},
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='id',
        ),
        migrations.RemoveField(
            model_name='expertuser',
            name='contact',
        ),
        migrations.AddField(
            model_name='administrator',
            name='admin_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='administrator',
            name='admin_name',
            field=models.CharField(default='No yet', max_length=30),
        ),
        migrations.AddField(
            model_name='administrator',
            name='admin_password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='expertuser',
            name='corresponding_user_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='corresponding_expert_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='corrsponding_admin_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='has_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='phonenumber',
            field=models.CharField(default='00000000', max_length=11),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='type',
            field=models.IntegerField(default=1, max_length=3),
        ),
        migrations.DeleteModel(
            name='BuyResources',
        ),
        migrations.DeleteModel(
            name='LikeResources',
        ),
    ]
