# Generated by Django 2.0.5 on 2019-05-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TechResource', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_context', models.CharField(default='Nothing has been written here', max_length=6000)),
                ('report_time', models.DateTimeField(auto_now_add=True)),
                ('report_resource_id', models.ForeignKey(on_delete=True, to='TechResource.SciAchi')),
                ('report_user', models.ForeignKey(on_delete=True, to='User.NormalUser')),
            ],
            options={
                'verbose_name': '举报信息',
                'verbose_name_plural': '举报信息',
            },
        ),
    ]
