# Generated by Django 2.0.5 on 2019-05-25 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TechResource', '0003_sciachi_author'),
        ('User', '0006_auto_20190525_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeResources',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('like_resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechResource.SciAchi')),
                ('liker_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.NormalUser')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
            },
        ),
    ]
